# Site settings
title: Digital Alchemy
email: leo.@live.com
description: "This Amazing site was built using jekyll on github pages. This blog was put together toi aid learning in the Founders and Coders course"
baseurl: "/leodev"
url: "http://yourdomain.com"
twitterUsername: CodersandCoffee
# Build settings
markdown: kramdown
permalink: pretty
